x-airflow-common:
  &airflow-common
  build: .
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    PYTHONPATH: /opt/airflow
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    AWS_REGION: ${AWS_REGION}
    S3_BUCKET: ${S3_BUCKET}
    SF_ACCOUNT: ${SF_ACCOUNT}
    SF_USER: ${SF_USER}
    SF_PASSWORD: ${SF_PASSWORD}
    SF_DATABASE: ${SF_DATABASE}
    SF_SCHEMA: ${SF_SCHEMA}
    SF_WAREHOUSE: ${SF_WAREHOUSE}
    SF_ROLE: ${SF_ROLE}
    TMDB_API_KEY: ${TMDB_API_KEY}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./pipeline:/opt/airflow/pipeline
    - ./logs:/opt/airflow/logs
    - ./config.py:/opt/airflow/config.py
    - ./.env:/opt/airflow/.env
    - ./tmdb_dbt:/opt/airflow/tmdb_dbt
    - /var/run/docker.sock:/var/run/docker.sock
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      - postgres
      - airflow-init

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always
    depends_on:
      - postgres
      - airflow-init

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init &&
        airflow users create \
          --username admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com \
          --password admin
    environment:
      <<: *airflow-common-env
    depends_on:
      - postgres

  dbt:
    build:
      context: .
      dockerfile: Dockerfile.dbt
    container_name: tmdb-pipeline-dbt-1
    volumes:
      - ./tmdb_dbt:/opt/dbt
      - ./.env:/opt/dbt/.env
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  postgres-db-volume: